### PR TITLE
Make flake8 as picky as possible

### PR DESCRIPTION
**Pull request by sirosen**
Enable all rules which are ignored by default, make minor code changes to comply.

Relevant to #83 , but does not close it.

### CODE REVIEW

**Comment by corpulentcoffee** [comment]
I *think* that when you use `select`, you need to re-list the codes that would have been enabled by default had you omitted `select` altogether. When I tried it, the proposed configuration succeeds in turning on new checks but it also turns off others.

```
(.venv3) ~/Repos/globus-sdk$ cat >test.py
print("hola"); print("mundo")

d = {
    'hola': 'mundo',
    'hello': 'world',
    }
^D

(.venv3) ~/Repos/globus-sdk$ git checkout master 
Switched to branch 'master'
Your branch is up-to-date with 'upstream/master'.

(.venv3) ~/Repos/globus-sdk$ flake8 test.py
test.py:1:14: E702 multiple statements on one line (semicolon)

program returned status code 1
(.venv3) ~/Repos/globus-sdk$ git fetch upstream pull/84/merge && git checkout FETCH_HEAD
. . .
HEAD is now at 4d2ae69... Merge 6a2a9018a84b450cedaa297e2a303f7ea1bf8aee into f3a3743d7dd3017f6c0c8958d548d9de610cf7dc

(.venv3) ~/Repos/globus-sdk$ flake8 test.py
test.py:6:5: E123 closing bracket does not match indentation of opening bracket's line

program returned status code 1
```

Luckily, I think `ignore` has the same behavior, so I tried using an empty ignore list (i.e. `ignore = `), and it *seems* to work and output both checks:

```
(.venv3) ~/Repos/globus-sdk$ flake8 test.py 
test.py:1:14: E702 multiple statements on one line (semicolon)
test.py:6:5: E123 closing bracket does not match indentation of opening bracket's line
```

**Comment by sirosen** [comment]
Yep, this usage of `select` was wrong. I've switch to the `ignore =` style.


As a quick aside, at least one older version of `flake8` (2.5.4) doesn't handle `--ignore ""` correctly and treats that equivalently to no explicit ignore list. Upgrading `flake8` resolved that issue for me, and `test-requirements.txt` specifies > 3.0.

**Comment by jaswilli** [comment]
Are `W503` and `W504` conflicting?

**Comment by sirosen** [comment]
What is `W504`? I can't find it in the [pycodestyle docs](https://pycodestyle.readthedocs.io/en/latest/search.html?q=W504).

**Comment by jaswilli** [comment]
I know, it's sort of mysterious but the bits and pieces I was able to gather from googling makes me think it's the opposite behavior of `W503`.

**Comment by sirosen** [comment]
We discussed, and agreed to remove those two rules because of the potential conflict.
Details in the commit message.

**Pull request merged**
